
seml:
  executable: scripts/feynman-network-subexperiment-v2-simplexcompare.py
  name: feynman-network-modular-7-baseline
  output_dir: seml-experiments/feynman-network-modular-7-baseline/log
  project_root_dir: ../../
  conda_environment: torch-cuda

slurm:
  experiments_per_job: 1
  max_simultaneous_jobs: 200
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 5G          # memory
    cpus-per-task: 2  # num cores
    time: 0-04:00     # max time, D-HH:MM

fixed:
  MAX_TRAIN_ITERS: 20000
  N_TEST_POINTS: 30000
  TEST_COMPACTIFICATION: 0.8
  MAX_BATCH_SIZE: 30000
  spreadsheet: "/om2/user/ericjm/precision-ml/equations.csv"
  lr: 1e-3
  activation: "ReLU"

I814:
  fixed:
    eqn: "I.8.14"
  grid:
    depth:
      type: choice
      options:
        - 4
        - 6
    width:
      type: choice
      options:
        - 6
        - 8
        - 10
        - 12
        - 14
        - 16
        - 18
        - 20
        - 25
        - 30
        - 45
        - 60
        - 90
        - 120
        - 180
        - 360
        - 720
    seed:
      type: choice
      options:
        - 0
        - 1
        - 2
        - 3

II615a:
  fixed:
    eqn: "II.6.15a"
  grid:
    depth:
      type: choice
      options:
        - 6
        - 9
    width:
      type: choice
      options:
        - 6
        - 8
        - 10
        - 12
        - 14
        - 16
        - 18
        - 20
        - 25
        - 30
        - 45
        - 60
        - 90
        - 120
        - 180
        - 360
        - 720
    seed:
      type: choice
      options:
        - 0
        - 1
        - 2
        - 3






